version: '3.8'

services:
  backend:
    build:
      context: ./java_backend/j_calculator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./js_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

networks:
  app-network:
    driver: bridge
